/* ============================================================
   taunts.js — every taunt line in one place. Data only, no logic.
   Loaded before gamekit.js; Gamekit.taunt() reads window.TAUNT_LINES.

   TO ADD A GAME'S FLAVOUR: add a block under its folder name (the URL
   segment, e.g. "chess", "connect-four") with any of the categories
   below. Missing categories just use the generic pool. No other file
   needs touching — Gamekit works out the game from the page URL.

   TO ADD A LINE: push a string onto the right array. Keep them short.

   WRITING RULE: a line must be true whenever its category fires. Players
   also lose by resigning and play humans over WhatsApp, so a `loss` line
   shouldn't claim checkmate or "the AI". Say what the category guarantees.

   Categories (the generic pool, `_`, has all of them), and WHEN each fires:
     loss        you lost: to the AI, to a person, or by resigning
     reversal    you lost after being praised by a `confidence` line
     confidence  you're clearly ahead mid-game (vs the AI or pass-and-play)
     lastChance  you're clearly behind / facing a killer threat
     win         you won (vs the AI, or the winner's view of a WhatsApp game)
     forfeit     you won because your opponent resigned (WhatsApp)
     draw        nobody won
   A game block may also invent its own category and call it by name,
   e.g. Gamekit.taunt("boom") — then only the game's lines are used.
   In a game block the shared categories are mixed with the generic pool
   (the game's own lines are picked about half the time).
   ============================================================ */
window.TAUNT_LINES = {
  _: {
    loss: [
      "Tough loss. Really tough.",
      "That's gonna leave a mark.",
      "Skill issue.",
      "Well, that happened.",
      "Painful to watch, honestly.",
      "Not your best game, champ.",
      "L + ratio.",
      "Your opponent is already bragging about this.",
      "Maybe try a different game. Or a different hobby.",
      "Better luck next time — you'll need it.",
      "Someone call it. Time of defeat: now.",
      "That was almost impressive. Almost.",
      "Was that... on purpose?",
      "A valiant effort. A losing one, but valiant.",
      "This is going straight in the group chat.",
      "Congratulations, you played yourself.",
      "Bold strategy. Didn't work though.",
      "Legends say they're still laughing.",
      "History will remember this. Unkindly.",
      "The scoreboard remembers.",
      "That's a screenshot for later.",
      "Someone's getting roasted in the group chat.",
      "Not the comeback story you were hoping for.",
      "They really thought they had it.",
      "Defeat looks great on you, somehow.",
      "The algorithm predicted this.",
      "Even the AI felt bad for a second. A second.",
      "That's one for the blooper reel.",
      "Someone update the leaderboard. Downward.",
      "A real character-building moment, that one.",
      "No notes. Just losses.",
      "The streak is dead. Long live the streak-ender.",
      "You brought a spoon to a sword fight.",
      "Somewhere, a trophy just cried.",
      "That was a choice. Not a good one.",
      "Rematch? Or therapy?",
      "Winners write history. You wrote a footnote.",
      "Lesson learned. Probably not, but still.",
      "A loss is just a win in a smaller font.",
      "That game owes you an apology. It won't give one.",
      "The good news: it can only go up from here.",
      "You didn't lose. You just finished second. Alone.",
    ],
    reversal: [
      "Ouuu, spoke too soon.",
      "“You've got this in the bag,” they said.",
      "Famous last words.",
      "That confidence aged like milk.",
      "Counting chickens before they hatch, huh?",
      "Should've knocked on wood.",
      "Turns out the bag had a hole in it.",
      "Premature celebration detected.",
      "That escalated quickly.",
      "Plot twist nobody asked for.",
      "The bag. It had legs. It ran.",
      "Hubris: a cautionary tale.",
      "The overconfidence tax has been collected.",
      "Should've stayed humble. Too late now.",
      "That prediction aged in dog years.",
      "Victory was declared a bit early there.",
      "The universe has a sense of humor.",
      "Jinxed. Thoroughly jinxed.",
      "That lead had an expiry date.",
      "From hero to zero. Fast.",
      "Saw the finish line. Tripped over it.",
      "Peaked early.",
      "The lead was a loan. They collected.",
      "You were winning. Technically. For a while.",
      "The comeback was theirs. The meltdown, yours.",
    ],
    confidence: [
      "You've got this in the bag.",
      "This one's basically over.",
      "Victory lap incoming?",
      "Looking pretty comfortable over there.",
      "Hard to see how this doesn't go your way.",
      "They might want to just forfeit now.",
      "Don't get too comfortable... actually, go ahead.",
      "This is looking like a blowout.",
      "Someone's about to update their bio to \"undefeated.\"",
      "Start drafting the victory speech.",
      "This might be the easiest win of the day.",
      "They're already celebrating. A little early, maybe.",
      "At this rate, it's basically a formality.",
      "The other side might want to tap out.",
      "Smooth sailing from here. Probably.",
      "This is what domination looks like.",
      "The vibes are immaculate.",
      "Comfortable lead. Dangerous feeling.",
      "Everything's going to plan. Suspicious.",
      "You're cooking. Keep the heat on.",
      "If this were a movie, this is the cocky montage.",
      "Savour this. It may not last.",
      "Right now, you're the main character.",
    ],
    lastChance: [
      "This is the part where you panic, right?",
      "One more slip and it's over.",
      "Living dangerously, huh?",
      "Still time to run.",
      "Hope you've got a backup plan. You don't. But hope anyway.",
      "This is fine. (It is not fine.)",
      "Down bad.",
      "It's not looking good — and it's about to look worse.",
      "The walls are closing in.",
      "This is the nervous part.",
      "No pressure. (So much pressure.)",
      "One wrong step and it's over.",
      "The margin for error just hit zero.",
      "Nowhere left to hide.",
      "Last call.",
      "Swing big. It's all you've got.",
      "Plot armor, please.",
      "Behind, but the story isn't over. Probably.",
      "Now would be a great time for a genius move.",
      "Down, not out. (Mostly down.)",
      "You're the underdog. Underdogs sometimes win.",
      "The crowd goes quiet.",
    ],
    win: [
      "Flawless. Insufferable, but flawless.",
      "Add it to the trophy shelf.",
      "Humble yourself. Or don't.",
      "That's one for the highlight reel.",
      "Absolutely cooked them.",
      "Screenshot this. For legal reasons.",
      "Your opponent has left the chat. Emotionally.",
      "GG. Mostly the G's.",
      "Smooth. Suspiciously smooth.",
      "Victory tastes like a group-chat victory lap.",
      "Was there ever any doubt? (There was a little.)",
      "Somebody get this person a cape.",
      "That's a W. Frame it.",
      "Gloating is legal here. Proceed.",
      "Your opponent is typing... and deleting.",
      "Victory music is playing. Only you can hear it.",
      "Another one for the legend.",
      "Great success!",
      "The group chat is about to hear about this.",
    ],
    forfeit: [
      "They folded. You didn't even have to finish.",
      "A win by resignation: the quiet kind of victory.",
      "They saw it coming and left early.",
      "Your opponent read the room and exited.",
      "Victory by forfeit. Nobody's judging. Much.",
      "They tapped out. You earned a nap.",
      "Sometimes the best move is theirs: quitting.",
      "Win accepted with grace. And a smirk.",
      "They ran. You win. That's the whole story.",
      "A rage quit, but a polite one.",
      "They took the exit. You took the win.",
      "White flag waved. Victory yours.",
      "Your opponent gave up early. How rude.",
      "You win by \"they couldn't be bothered.\"",
      "A walkover. Enjoy the stroll.",
      "They left before the final scene.",
      "Resignation received. Trophy yours.",
      "You didn't win it. They handed it over.",
    ],
    draw: [
      "Nobody won. Everyone's a little embarrassed.",
      "A draw: the participation trophy of games.",
      "Peace was never an option. Yet here we are.",
      "So much effort. So little result.",
      "Two enter, none leave victorious.",
      "Perfectly balanced. Perfectly unsatisfying.",
      "Rematch. You both know it.",
      "An honourable draw. Dishonourable feelings.",
      "A tie: the game's way of saying \"try again.\"",
      "Split the glory. Keep the grudge.",
      "So close to a winner. So far.",
      "Everyone gets a participation trophy. Nobody wants it.",
      "Everyone shook hands. Nobody smiled.",
      "It's a tie, so neither of you gets bragging rights.",
      "A draw: the most polite way to disappoint everyone.",
      "Even stalemates have standards. This one didn't.",
      "The game ended. The argument begins.",
      "Zero winners, two rematch requests.",
    ],
  },

  // ---- per-game flavour: add a block per game folder ----------------

  // vs the AI, local 2-player, or WhatsApp (so lines never assume mate or "the AI"
  // unless the category only fires against the AI: confidence, lastChance).
  chess: {
    loss: [
      "Your king has left the building.",
      "Somewhere, a grandmaster just winced.",
      "The pawns were brave. You were not.",
      "Even your knight is embarrassed, and he moves in an L.",
      "Your rooks never even got to leave the corner.",
      "Blunder count: classified. Feelings: hurt.",
      "That's what the opening books were for.",
      "Your bishops would like a word. Diagonally.",
      "Your queen wanted to help. You didn't let her.",
      "A pawn could've saved you. You sent it to die in the opening.",
      "En passant? More like en passed out.",
      "You hung a piece. Then you hung your head.",
      "The fork was real. The knight was smug.",
      "Your king walked into the open like a tourist.",
      "The endgame called. It wanted to talk about your choices.",
      "Your rating just filed a complaint.",
    ],
    win: [
      "Checkmate. Say it slowly for the cheap seats.",
      "The queen sends her regards.",
      "Add \"tactician\" to your bio.",
      "Absolute cinema.",
      "That king never stood a chance. Neither did his rooks.",
      "Your pawns marched. Their king did not.",
      "Fork, pin, skewer. You cooked a whole meal.",
      "Their king ran out of squares and excuses.",
      "That endgame was a masterclass. Pretend it was planned.",
      "The knights approve. Those horses never lie.",
      "Mate. As in \"check\", but forever.",
      "You out-thought a whole army. Casual.",
      "Time to tell people you \"play chess.\"",
      "Zugzwang? More like zug-zwon.",
    ],
    draw: [
      "Neither king blinked.",
      "A draw: chess for \"we're both too stubborn.\"",
      "Hours of thinking, zero winners.",
      "Everyone shook hands. Nobody meant it.",
      "A draw. The chess equivalent of a shrug.",
      "Nobody won, but the pieces got plenty of exercise.",
      "Both kings survived. Both egos didn't.",
      "Peace in our time. Nobody wanted it.",
      "The most polite way to not lose.",
      "A draw: because winning would've required courage.",
      "Kings, in the end, just sat there.",
      "All that calculating for a handshake.",
      "Somewhere, a grandmaster calls this \"a solid result.\"",
      "A draw is a loss for both of you, spiritually.",
    ],
    // fires when you're up about a minor piece against the AI
    confidence: [
      "A whole piece up. Try not to hang the rest.",
      "Up material, down to not blundering it away.",
      "The pieces are on your side. Don't make it weird.",
      "Trade everything, simplify, win. (Easier said than done.)",
      "They're down a piece and a plan.",
      "Ahead on material. The hard part: staying ahead.",
      "Piece up. Time to trade down and look smug.",
      "Material advantage: the closest chess gets to a free lunch.",
      "A free piece is a free piece. Take it home.",
      "The extra piece is whispering \"simplify.\"",
      "You're winning. Absolutely do not stalemate them.",
      "They're missing a piece and a smile.",
      "A clean extra piece. Hang on to it like a toddler with a snack.",
    ],
    // fires when the AI is up about a minor piece
    lastChance: [
      "Down a piece. Time for swindles.",
      "Material says no. Imagination says maybe.",
      "A piece down: now's the time for a miracle.",
      "Behind on pieces. Ahead on potential. (Allegedly.)",
      "Dig deep and find the trap. There's always a trap. Hopefully.",
      "The AI is winning on paper. Paper doesn't play chess.",
      "Complicate it. Confuse it. Pray.",
      "Down a piece: that's a \"tactics or bust\" moment.",
      "The odds are low. The swindle potential is high.",
      "Sacrifice something shiny. Distract them.",
      "Behind, but the position is still alive. Somewhere.",
      "Move like you have a plan. Even if you don't.",
      "This is where legends are made. Or squished.",
      "Start a counterattack. Or a prayer.",
      "Worth a shot: attack the king. Always attack the king.",
      "If it gets worse, you can always blame the lag.",
    ],
    reversal: [
      "Up a piece, and yet.",
      "The extra piece went home early.",
      "From winning to... this. A chess journey.",
      "You had material. They had a plan.",
      "That lead had a one-way ticket.",
      "You had a piece up. They had a better idea.",
      "From \"easy win\" to \"what happened\" in under ten moves.",
      "Up a piece, down the tablecloth.",
      "It was going so well. It always is until it isn't.",
      "All that material, and the king still fell.",
      "Ahead on pieces, behind on common sense.",
      "A knight up is still just a knight if you hang the king.",
      "The queen was up. The king was out.",
      "Lesson: pieces don't win games. Checkmate does.",
    ],
  },

  checkers: {
    loss: [
      "You got jumped. Repeatedly.",
      "Kinged and humbled.",
      "Your pieces have left the chat.",
      "Double-jump energy was not on your side.",
      "Somebody stole your lunch money and your last king.",
      "Your last piece is still looking for a way home.",
      "Checkers is just chess with fewer excuses. You found some anyway.",
      "They hopped. You flopped.",
      "Forced jumps are brutal. You jumped right in.",
      "You fed them pieces like it was a buffet.",
      "The back row was open. They didn't ask permission.",
      "Your pieces went forward. They didn't come back.",
      "You blinked. They crowned.",
      "The mandatory jump got you. It always gets someone.",
    ],
    win: [
      "King me. Then king me again.",
      "Jumped, kinged, finished.",
      "Hop, skip, win.",
      "Crowned and conquered.",
      "Their pieces never saw the jumps coming.",
      "Double jump! Triple jump! Total domination!",
      "You kinged yourself and then everyone else.",
      "A real crown-pleaser.",
      "Their back row stood no chance.",
      "Forced jump? Forced win.",
      "Your pieces hopped to glory.",
      "They fed you pieces. You ate well.",
      "Not a king left on their side. Cold.",
    ],
    // fires when you're ~two pieces up
    confidence: [
      "Look at all that material.",
      "Two pieces up and smug about it.",
      "Your side is crowded. Theirs is spacious.",
      "King incoming?",
      "You're ahead. Don't leave a piece hanging out to dry.",
      "Pieces up and a path to the crown. Nice.",
      "Careful: forced jumps can turn a lead into a trap.",
      "You're ahead. Keep your back row home.",
      "Two up. Now, trade down.",
      "Their side is looking empty. Yours, lively.",
      "Ahead by two. Just don't walk into a double jump.",
      "A healthy lead. Now don't get jumpy.",
      "A lead is a lead. Protect it like your last cookie.",
    ],
    // fires when the AI is ~two pieces up
    lastChance: [
      "Two pieces down. Time to start jumping.",
      "Outnumbered. Make the jumps count.",
      "Your side of the board is looking spacious.",
      "Time for a king-sized comeback.",
      "They're ahead. Make them regret it.",
      "Down on pieces, but one lucky double-jump fixes everything.",
      "Behind on pieces. Hunt for a double jump.",
      "Set a trap. They have to jump. Use it.",
      "Forced jumps are a gift if you plan it. Plan it.",
      "Down two. The comeback begins with a sacrifice.",
      "Sacrifice one, win two. That's the dream.",
      "A trap, a jump, a miracle. In that order.",
      "Remember: they must jump. Use their obedience.",
      "They're ahead, but forced jumps equalise anything.",
    ],
    reversal: [
      "From two pieces up to this. Hmm.",
      "Jumped on at the last second.",
      "The lead jumped ship.",
      "All that material, and they still found the jumps.",
      "Two pieces up, and yet.",
      "You hopped ahead. They hopped further.",
      "A double jump ruined your whole plan.",
      "You were crowned and then... not.",
      "Up two? Down all. Impressive swing.",
      "You were winning. Now you're a cautionary tale.",
      "The lead fell off the back row.",
      "You forgot about the forced jump. Classic.",
      "A lead on the board isn't a lead on the scoreboard.",
      "The lead was a trap. You were the bait.",
    ],
  },

  "connect-four": {
    loss: [
      "Four in a row was always the plan. Just not yours.",
      "You saw it coming. You let it happen.",
      "Gravity: 1. You: 0.",
      "You dropped the ball. And the disc.",
      "Seven columns. Wrong one every time.",
      "Every disc you dropped helped them, somehow.",
      "That's a lot of columns to block and not a lot of blocking.",
      "You were one disc short of a miracle.",
      "You built a wall. They built a four.",
      "You played the columns. They played you.",
      "They saw the diagonal. You saw a column.",
      "That diagonal was visible from space.",
      "The middle column called. You didn't answer.",
      "Red or yellow, you were blue.",
      "You tried to connect four. They connected the dots.",
      "That column was a one-way street to defeat.",
    ],
    win: [
      "Four in a row, one smug grin.",
      "Gravity helped. You did the rest.",
      "Drop the mic. Or the disc. Both.",
      "Pick a column, any column. You picked well.",
      "A diagonal victory. Elegant and sneaky.",
      "You dropped the perfect disc. Twice.",
      "Connect four: connected. Ego: also connected.",
      "They never saw the trap coming.",
      "Your discs lined up like they rehearsed it.",
      "You out-stacked them.",
      "Your opponent is staring at the board in silence.",
      "Disc by disc, you built a winner.",
    ],
    draw: [
      "The board is full and so is everyone's patience.",
      "Forty-two discs, zero glory.",
      "A full board and an empty victory.",
      "Every column maxed out. No winner. Wild.",
      "You both blocked well enough to ruin the fun.",
      "Forty-two discs, forty-two reasons to rematch.",
      "Nobody got four. Everybody got tired.",
      "The board is full. The scoreboard is not.",
      "All that blocking and no winner. Respect.",
      "You both won the \"don't lose\" award.",
      "Yellow blocks red. Red blocks yellow. Nobody wins.",
      "Not a four in sight. Just stacks of effort.",
      "Gravity ran out of room. So did the game.",
      "Technically nobody lost. Practically everyone did.",
    ],
    // fires when the AI has the stronger position
    lastChance: [
      "The AI is building something. Check the diagonals.",
      "They always get you on the diagonals.",
      "Their discs are lining up. Yours are... also there.",
      "If you don't block now, you'll be blocked later.",
      "Three in a row is a warning, not a suggestion.",
      "Block first, panic second.",
      "Your middle column is looking suspiciously empty.",
      "The AI has a plan. It's not a nice one.",
      "A double threat is coming. Don't let it.",
      "Can you stop two threats at once? Practise now.",
      "Their discs are forming a shape. Break it.",
      "It's not too late. It's just late.",
      "Time to defend like your life depends on it. Mild exaggeration.",
      "Blocking is boring until it saves you.",
    ],
    // fires when you have the stronger position (vs AI, or named in 2-player)
    confidence: [
      "Your discs are lining up nicely.",
      "Look at that board presence.",
      "They'd better start blocking. Fast.",
      "Three-in-a-row energy.",
      "Stay calm. Fours don't build themselves.",
      "Your threats are stacking. So are the odds in your favour.",
      "Two ways to win and one way to lose. Be careful.",
      "This is starting to look inevitable.",
      "Your discs have real chemistry.",
      "Don't rush the finish. Close it cleanly.",
      "That's a shape that spells trouble. For them.",
      "They can't block everything. Can they?",
      "Smell that? That's a four cooking.",
    ],
    reversal: [
      "So close to four. So, so close.",
      "You had the lead. Then gravity had opinions.",
      "Threes are great. Fours are better.",
      "All those almost-fours, and it ended like this.",
      "Your lead slid out of the bottom row.",
      "From three in a row to zero in a row.",
      "You had the diagonal. They had the answer.",
      "A glorious setup that never closed.",
      "They blocked, then they built. Rude.",
      "You gave them the column. They said thanks.",
      "Close doesn't count in Connect Four.",
      "You were one move from victory. One.",
      "It was going so well, and then gravity.",
    ],
  },

  // lastChance fires when the AI has two winning threats at once (a fork)
  "tic-tac-toe": {
    loss: [
      "You lost at tic-tac-toe. Let that sink in.",
      "Three in a row. Not hard. Apparently.",
      "Nine squares. Plenty of space to lose in.",
      "Somewhere, a pigeon is better at this.",
      "X marks the spot where you went wrong.",
      "A game solved decades ago, and you still lost it.",
      "The most famous draw in history, and you couldn't even get that.",
      "A child could've drawn it.",
      "Draws are free. You didn't take one.",
      "Tic-tac-toe has a safe strategy. You ignored it.",
      "You let them take the corner. Rookie error.",
      "It's called \"draw if you try.\" You didn't.",
      "You've been out-X'd. Or out-O'd. Whichever.",
      "Somewhere, a toddler is laughing.",
      "Next time, take the centre. That's the whole trick.",
      "That was the easiest game to not lose.",
    ],
    win: [
      "Beating tic-tac-toe: the bare minimum, achieved.",
      "A game anyone can play. You won it anyway.",
      "Three in a row, zero chill.",
      "Genius level: tic-tac-toe champion.",
      "The corner trick worked. Of course it did.",
      "You beat a solved game. Take the win.",
      "Not many people win this. You did.",
      "X marks the spot. You found it.",
      "Fork delivered. Opponent devastated.",
      "Add \"tic-tac-toe champion\" to your CV.",
      "Two threats at once. Beautiful.",
    ],
    draw: [
      "Tic-tac-toe ends in a draw. Shocking. Truly.",
      "Cat's game. Meow.",
      "Nobody won, as the ancient prophecy foretold.",
      "Both of you played perfectly. Or equally badly.",
      "A draw, the most dignified tic-tac-toe result.",
      "Perfect play from both sides. Boring, but perfect.",
      "The cat wins. As usual.",
      "Nobody lost, nobody won, everybody's bored.",
      "Another draw for the history books. Spoiler: it's most of them.",
      "Meow. The cat's game strikes again.",
      "You both played it safe. Congratulations.",
      "The most common result in tic-tac-toe history.",
      "No fork, no glory.",
      "A draw, which, in this game, is the correct answer.",
    ],
    lastChance: [
      "That's a fork. That's a fork!",
      "Two threats, one you. Good luck.",
      "Oh. Oh no. Oh no no no.",
      "You can only block one of them.",
      "The fork. The dreaded fork.",
      "Two ways to win and you can stop one.",
      "Fork incoming. Hold on to something.",
      "They've got two paths. You've got one move.",
      "A fork in the road. And it's pointy.",
      "The AI is smiling. You can tell.",
      "Block one, lose to the other. Beautiful design.",
      "You can't defend this. But sure, try.",
      "Your move, by which we mean \"your only move.\"",
      "Two threats. Zero safe squares.",
    ],
  },

  reversi: {
    loss: [
      "Flipped. Flipped again. And again.",
      "Your whole board changed sides. Traitors.",
      "Your discs defected. All of them.",
      "Never trust a corner you don't own.",
      "Black or white, you ended up on the wrong side of it.",
      "Another day, another corner you didn't take.",
      "Your discs voted with their backs.",
      "They flipped your discs like pancakes.",
      "The corners were free real estate. You didn't build.",
      "You gave them the edge. All of it.",
      "Every disc you placed became theirs.",
      "The board turned against you, one flip at a time.",
      "Your discs were recruited by the opposition.",
    ],
    win: [
      "The board is yours. Most of it, anyway.",
      "Flip it and quit it.",
      "Corners captured, hearts broken.",
      "Your discs won the vote.",
      "Flip the script. And everything else.",
      "You turned the whole board. Show-off.",
      "Their discs have switched teams. Welcome.",
      "The corners were yours. The win followed.",
      "You stole their discs and their dignity.",
      "That's called a hostile takeover.",
      "Reverse psychology worked. Reverse board, too.",
      "They'll feel that flip for days.",
    ],
    draw: [
      "A tie: equal discs, equal disappointment.",
      "Dead even. Somebody flip a coin. Or a disc.",
      "Exactly as many discs each. Suspicious.",
      "Perfectly split. The board is undecided.",
      "Black and white, perfectly gray.",
      "The board split in half. So did the result.",
      "Nobody wins. Everybody flips.",
      "A tie: the rarest result in Reversi. Treasure it.",
      "You both flipped well. Neither flipped best.",
      "Half the board each. Zero winners.",
      "Same disc count. Different levels of annoyed.",
      "You'll have to settle this with another game.",
      "A tie: the universe's way of saying \"rematch.\"",
    ],
    // leader on discs — early disc leads are famously a warning label in reversi
    confidence: [
      "Lots of discs. Don't count your flips.",
      "Big disc lead. In Reversi, that's a warning label.",
      "The board is turning your colour.",
      "Ahead on discs. Whether that's good is a Reversi mystery.",
      "Disc lead! The corners will decide if it was real.",
      "A disc lead this early? Suspicious, but nice.",
      "Lots of discs. Few corners. Hmm.",
      "In Reversi, fewer discs sometimes means more power. Just saying.",
      "The numbers look good. Reversi doesn't care about numbers.",
      "You've got the colour. Do you have the corners?",
      "Don't get cocky. Flips are fast.",
      "The more discs you have, the more they can flip.",
      "You're winning on discs. Now win on corners.",
    ],
    // the trailing player when the other leads on discs
    lastChance: [
      "Behind on discs? That's classic Reversi strategy. (Say it with confidence.)",
      "Fewer discs, more options. Tell yourself that.",
      "The comeback starts with a corner.",
      "Fewer discs now just means more flips later.",
      "Disc count lies. Mostly.",
      "You have fewer discs. Sometimes that's a strategy.",
      "Fewer discs means fewer targets. Optimism!",
      "Wait for them to run out of safe moves.",
      "Edges first, glory later.",
      "Reversi is won in the last ten moves.",
      "Make them move into the danger squares.",
      "Don't flip too much. Let them overextend.",
      "Mobility is the real score. Ask anyone.",
      "They're ahead. Make them regret each disc.",
    ],
    reversal: [
      "Disc lead gone. Poof.",
      "All those discs, flipped away in a heartbeat.",
      "The flips giveth. The flips taketh away.",
      "Ahead on discs, behind where it counts.",
      "The lead looked solid. The corner disagreed.",
      "You flipped too much, too soon.",
      "They waited. You rushed.",
      "You had the board. They had the corners.",
      "A mountain of discs, then a landslide.",
      "Your discs switched sides at the worst time.",
      "You won the middle. They won the end.",
      "You were counting discs. They were counting corners.",
      "The board flipped. And so did the result.",
    ],
  },

  mancala: {
    loss: [
      "Your stones all went home with them.",
      "Sowed the seeds. They harvested.",
      "Your store is looking a bit empty.",
      "All that sowing, no reaping.",
      "Stones don't lie. They just left.",
      "The oldest game in the book, and you found a new way to lose it.",
      "Your pits ran dry.",
      "Somebody should've counted the seeds.",
      "Your last move was a long walk to nowhere.",
      "Every stone you sowed ended up in their store.",
      "They got an extra turn. You got an extra loss.",
      "You emptied your pits for them.",
      "Their store overflowed. Yours echoed.",
      "Somewhere, an ancestor shakes their head.",
    ],
    win: [
      "Stones collected, ego inflated.",
      "The harvest is yours.",
      "Your store overflowed. Theirs did not.",
      "Ancient game, modern smugness.",
      "More stones, more swagger.",
      "That capture was surgical.",
      "You saw the extra turn before they did.",
      "A perfectly sown victory.",
      "Your store looks heavy. Heavy with glory.",
      "You played the pits like a piano.",
      "They emptied their side. You filled yours.",
      "You stole their stones and their dreams.",
      "Harvest day. The harvest is you.",
    ],
    draw: [
      "Exactly equal stones. Perfect and pointless.",
      "A tie in an ancient game. The ancestors are unimpressed.",
      "Even-steven, down to the last stone.",
      "Balanced as all things should be. Annoying.",
      "A tie: the stones refuse to choose.",
      "Every stone accounted for. No winner.",
      "A tie: the ancient way of saying \"again.\"",
      "The ancestors shrug.",
      "Not a single stone out of place. Nobody won.",
      "You both sowed the same. And reaped the same.",
      "The stones can't agree on a winner.",
    ],
    // leader on stores
    confidence: [
      "Your store is filling up nicely.",
      "Hoarding stones like a dragon.",
      "Stones in the store are stones you keep.",
      "That store is looking heavy.",
      "You're ahead on stones. Keep your pits guarded.",
      "A big lead, but the stones can still shift.",
      "Keep an eye on captures. They're sneaky.",
      "Don't empty your pits too fast.",
      "Your side is stacked. Their side is stressed.",
      "A strong lead. Watch the extra turns.",
      "Don't leave a gap for them to capture.",
      "Stone hoarder detected.",
      "Their store's looking a bit light.",
    ],
    // the trailing player
    lastChance: [
      "Your store is looking a little sparse.",
      "Time to sow something good.",
      "Every stone counts now. Ancient wisdom.",
      "Capture something. Anything.",
      "An empty pit is a trap for them. Probably.",
      "Look for an extra turn. It's your best friend.",
      "Behind on stones. Time to set a capture.",
      "Their side has gaps. Find them.",
      "Keep your last pits full. Don't feed them.",
      "Use the extra-turn trick. Chain it.",
      "A big capture can change everything.",
      "Don't give them easy captures. That's rule one.",
      "One big capture could flip this.",
      "Don't empty the pit they're aiming at.",
    ],
    reversal: [
      "Leading by stones, losing by the end. A mancala special.",
      "The stones turned on you.",
      "So many stones. So few that mattered.",
      "Your store was ahead. Their store had other plans.",
      "A big lead, lost to one big capture.",
      "You were ahead. Then they weren't done.",
      "The extra turns got you. They always do.",
      "You had the stones. They had the timing.",
      "They emptied the right pit at the right time.",
      "It all went into their store in the end.",
      "The last sowing was theirs.",
      "Your pits ran dry at the worst time.",
      "A late capture stole the show.",
    ],
  },

  "dots-and-boxes": {
    loss: [
      "Boxed in. Literally.",
      "You drew the line. They drew the boxes.",
      "Never give away that third side. Never.",
      "You handed over boxes like party favours.",
      "The chain reaction was real.",
      "Dots: connected. Your hopes: not.",
      "A whole lot of boxes, and none of them yours.",
      "You should have counted the chains. Too late.",
      "You gave them the long chain. They said thanks.",
      "Third sides: the silent killer.",
      "They claimed boxes like they were free samples.",
      "You were out-chained.",
      "The double-cross was not in your favour.",
    ],
    win: [
      "More boxes, more bragging rights.",
      "Boxed them out.",
      "Square deal. Squarer win.",
      "Connect the dots. Collect the boxes.",
      "You took the long chain and the trophy.",
      "The long chain was yours.",
      "A box-collecting masterclass.",
      "Sacrificed two boxes, took six. Math!",
      "You saw the chain coming.",
      "You counted the chains. They lost count.",
      "Hold the third side. Win the game.",
      "They gave you the chain. You took it.",
    ],
    draw: [
      "Equal boxes. Equal dignity.",
      "A tie, so someone gave away a box somewhere.",
      "Perfectly square. Perfectly drawn.",
      "Everything is a draw. Even the lines.",
      "Equal boxes. Unequal egos.",
      "Neither of you could break the symmetry.",
      "You both drew. Literally.",
      "No chain was long enough.",
      "The game is a draw, the arguing is just starting.",
      "You both gave away exactly the same amount.",
      "Square one: rematch.",
      "Neither of you won the chain war.",
    ],
    // leader on boxes
    confidence: [
      "Boxes are piling up on your side.",
      "Look at those squares. All yours.",
      "That third-side trick is working for you.",
      "Boxes: yours. Doubt: theirs.",
      "Ahead on boxes. Count the chains.",
      "Careful with the endgame. Chains are tricky.",
      "You're collecting boxes like Pokémon.",
      "A lead on boxes. Keep an eye on the chain count.",
      "Keep the third side to yourself.",
      "Don't open the chain too early.",
      "Ahead, but keep control of the chains.",
      "Don't be the one to open the last chain.",
      "Your boxes are neatly tidied. Theirs, scattered.",
    ],
    // the trailing player
    lastChance: [
      "Careful with that third side. They're hungry.",
      "Fewer boxes? Time for a sacrifice play.",
      "Don't hand over another box.",
      "Chains are coming. Brace.",
      "Play the long game. Literally, the long chain.",
      "A double-cross could save you. Look for it.",
      "Try the sacrifice trick. Give two, take more.",
      "Count the chains before they count you.",
      "Don't open the long chain. Let them.",
      "Avoid the third side. Always.",
      "Fewer boxes isn't the end. Chains decide the end.",
      "Make them open the first chain.",
      "Sacrifice small, win big. Maybe.",
    ],
    reversal: [
      "From box leader to box donor.",
      "You gave away the chain, didn't you.",
      "The long chain strikes again.",
      "Ahead on boxes. Behind on the chain count.",
      "You were leading. Then the chain arrived.",
      "All those boxes, and you opened the long chain.",
      "The lead was a mirage. A box-shaped mirage.",
      "You gave away the last chain. Oops.",
      "You had the boxes. They had the parity.",
      "The double-cross got you.",
      "You forgot to count the chains. Classic.",
      "A lead built on short chains collapsed.",
      "You opened the wrong chain.",
    ],
  },

  pentago: {
    // confidence = one marble from five, with no threat from the other side;
    // lastChance goes to the other player. Rotations can undo it, hence the jokes.
    confidence: [
      "Four in a line. One marble from glory.",
      "Your marbles are lining up. Just don't lose them.",
      "One more marble. Then pray nobody rotates it away.",
      "That row is looking dangerous. For them.",
      "They're one rotation from ruining it. Keep an eye out.",
      "Four marbles aligned. The fifth is thinking about it.",
      "Your marbles are getting ideas.",
      "You're one marble away. Don't blink.",
      "Don't let a spin ruin your line.",
      "They have to break that line. Can they?",
      "A clean four-line. Chef's kiss.",
      "Keep the row safe from rotation.",
    ],
    lastChance: [
      "Four in a row over there. Rotate something. Anything.",
      "Spin it away or lose it.",
      "That's a threat. A spinning quadrant could fix it.",
      "Time to twist your way out of this.",
      "Break that line. With a spin if you must.",
      "They're one marble from five. Panic politely.",
      "A rotation could save you. Find it.",
      "Block the fifth spot. Or spin the whole row away.",
      "Twist the quadrant, twist the plot.",
      "Spin their row into a mess.",
      "You need a rotation miracle.",
      "Rotate their marbles away from each other.",
    ],
    reversal: [
      "One marble from five, and then the board spun.",
      "The quadrant giveth. The quadrant taketh away.",
      "So close to five. The rotation had other plans.",
      "You had the line. The spin took it.",
      "Four in a row, then zero. Magic.",
      "A rotation unmade your masterpiece.",
      "You were almost there. Then they spun.",
      "The final marble never arrived.",
      "The quadrant betrayed you.",
      "Spun out of your lead.",
      "You had the pressure. Then the pivot.",
      "A rotation ruined your row.",
    ],
    loss: [
      "The board spun, and so did your hopes.",
      "Spun out. Beautifully.",
      "Rotate your strategy. Or your sanity.",
      "You twisted when you should've stood still.",
      "Four quadrants, zero answers.",
      "The board turned on you. Literally.",
      "You placed a piece. They rotated the evidence away.",
      "Your marbles went missing. So did your win.",
      "Five in a row is hard. Getting rotated is harder.",
      "You were dizzy before the game even ended.",
      "The twist ending wasn't in your favour.",
      "You rotated the wrong quadrant. We all saw it.",
      "Your marbles are scattered. Like your plan.",
      "They used your quadrant against you.",
    ],
    win: [
      "Five in a row. Spin to win.",
      "You spun it right round.",
      "Twist and shout. Mostly shout.",
      "Quadrants conquered.",
      "Five in a row, and the board is yours.",
      "That rotation was criminal.",
      "You spun the board into a win.",
      "A twist of fate. A twist of the board.",
      "Marbles aligned like destiny.",
      "The final spin was pure art.",
      "You rotated your way to victory.",
      "That quadrant had it coming.",
    ],
    draw: [
      "A draw. Maximum spin, minimum result.",
      "The board spun, nothing changed.",
      "Everyone's dizzy. Nobody's won.",
      "A tie, after all that rotating. Tragic.",
      "You both ran out of marbles. And ideas.",
      "Both reached five at once? Or a full board. Either way, a draw.",
      "A rotation that made everybody happy. And nobody.",
      "The marbles are in place, but the glory isn't.",
      "Round and round and round we go. Draw.",
      "A draw: for those who like rotating in place.",
      "Quadrants cancelled each other out.",
    ],
  },

  // a confidence line means a player is one round from taking the match
  "rock-paper-scissors": {
    loss: [
      "Scissors cut you. Paper covered you. Rock hit you. It's all the same.",
      "It's a coin flip with extra steps, and you lost the coin flip.",
      "It's literally a one-in-three guess. How.",
      "Your rock was brave. Their paper was braver.",
      "Predictable. They saw you coming.",
      "Next time, try not to telegraph your hand.",
      "Three options, and you found the wrong one.",
      "Your opponent studies you. You study... nothing.",
      "You picked rock. Again. They noticed.",
      "Paper beats rock. Paper has been beating you all day.",
      "You lost a game of pure chance. That takes talent.",
      "They read you like a book. A short one.",
      "You threw the same thing three times. Creative.",
    ],
    win: [
      "Read their mind. Impressive and a little creepy.",
      "Mind reader. Or lucky. Don't say lucky.",
      "The hand never lies. Yours was right.",
      "Your hand was a sword. Theirs was a wet noodle.",
      "Rock, paper, scissors, victory.",
      "Three options and you picked the winning one. Again.",
      "You predicted them like a prophet.",
      "Scissors cut it. Paper covered it. Rock crushed it.",
      "They never saw it coming.",
      "You played the odds. And the person.",
      "Not luck. Skill. (Luck.)",
      "You've mastered the art of the throw.",
    ],
    // the leader is one round from the match while the other has none
    confidence: [
      "One more round and it's yours.",
      "Match point energy.",
      "Just one more. Don't get cocky.",
      "They are one round from a very bad day.",
      "Match point. Smooth hands now.",
      "One round and they're toast.",
      "They have scored nothing and you are one throw away. Do not choke.",
      "A clean sweep is in sight.",
      "The finish line is a rock away.",
      "They're in trouble. You're one throw from sealing it.",
      "Match point: the most dangerous kind of comfortable.",
      "A shutout is calling your name.",
      "You're ahead. Don't throw it away. (Pun intended.)",
    ],
    // the player on the wrong end when the other is one round from the match
    lastChance: [
      "One more loss and it's over. No pressure.",
      "Time to throw something unexpected.",
      "Change it up. They're reading you.",
      "Rock again? Bold. Or foolish.",
      "Everything rides on this hand.",
      "You need a win. Not a draw. A win.",
      "They can see right through you.",
      "The best defence is a surprising hand.",
      "The pressure's on. So is your fist.",
      "Don't throw the same thing again. Seriously.",
      "Think like them. Then do the opposite.",
      "The odds are against you. The hand is still yours.",
    ],
    reversal: [
      "So close to winning. Rock bottom now.",
      "Choked at match point.",
      "You were one round away. One.",
      "Match point: gone. Pride: also gone.",
      "You led. Then you lost. A rock-solid collapse.",
      "So close you could taste victory. Tasted defeat instead.",
      "Your hand failed at the worst time.",
      "One round from a clean sweep, one round from a disaster.",
      "They turned it around. You turned it over.",
      "That lead was paper-thin.",
      "Your confidence got scissored.",
      "A lead is just a suggestion in rock-paper-scissors.",
      "Rock, paper, scissors, regret.",
    ],
  },

  // "boom" = solo, you hit a mine. "clear" = solo, you cleared the board.
  // loss/win also fire in the WhatsApp race, where a loss may be on tile count
  // (not a mine), so those two stay general.
  minesweeper: {
    boom: [
      "You stepped on it. It was literally a mine.",
      "Click. Boom. Regret.",
      "The flags were right there.",
      "That number was a hint. You ignored it.",
      "Somewhere, a mine is very proud of itself.",
      "Bold of you to guess there.",
      "It said 3. You saw \"safe.\"",
      "The mine was minding its own business.",
      "\"Click with confidence,\" they said.",
      "That wasn't a guess. That was a donation.",
      "You clicked on a mine. A mine! In Minesweeper!",
      "50/50 odds, 100% regret.",
      "The numbers were trying to help you.",
      "That corner was a trap. Everyone knows.",
    ],
    clear: [
      "Every mine, dodged.",
      "Cleared the field. Shaking hands optional.",
      "Not a single boom. Smooth operator.",
      "Mines: 0. You: 1.",
      "Sweeper, certified.",
      "The minefield is now a meadow.",
      "You flagged. You cleared. You conquered.",
      "Logic: 1. Luck: 0 (mostly).",
      "Not one boom. Impressive.",
      "Every number made sense to you. Rare.",
      "The mines never stood a chance.",
      "You've defused the entire field.",
      "You didn't guess once. (You guessed twice.)",
    ],
    loss: [
      "Not every tile is a safe tile. Noted.",
      "The mines won this round.",
      "You tiptoed. It wasn't enough.",
      "Tiles lost, pride lost.",
      "A minefield is no place for a hot take.",
      "The mines are patient. They'll wait.",
      "One wrong click and it all comes down.",
      "You opened fewer tiles, or the wrong one. Either way.",
      "They out-swept you.",
      "The mines were hiding. The evidence wasn't.",
      "You can't win them all. Especially these.",
      "You lost. But the mines look satisfied.",
    ],
    win: [
      "Every mine, dodged.",
      "Not a single boom. Smooth operator.",
      "Mines: 0. You: 1.",
      "Tiptoed through the minefield like a pro.",
      "Safe tiles collected, ego intact.",
      "You swept more than they did.",
      "You found the safe tiles. They found the mines.",
      "The mines respect you.",
      "More tiles, no booms.",
      "You tiptoed beautifully.",
      "Zero mines hit. Maximum swagger.",
    ],
  },

  // WhatsApp race: whoever clears the board (or the opponent bails) wins
  "lights-out": {
    loss: [
      "Lights out. For you.",
      "They found the switch. You found the dark.",
      "You left a light on. They left none.",
      "Dark mode: activated. For you, emotionally.",
      "You pressed buttons. They pressed the right ones.",
      "The last light was theirs to turn off.",
      "You flipped the wrong switches.",
      "That board was a puzzle. You were the missing piece.",
      "They saw the pattern. You saw lights.",
      "One light stayed on. Of course it did.",
      "The grid looked at you and laughed.",
      "You tried to turn off the lights. The lights turned off you.",
      "Your brain flickered and went out.",
    ],
    win: [
      "You brought the dark. Nicely done.",
      "Lights out for them. Lights up for you.",
      "Not a single light left. Tidy.",
      "Every light, extinguished. Genius.",
      "You solved it. They stared at it.",
      "Click by click, you ended the glow.",
      "The grid is dark. Your future is bright.",
      "Lights: off. Ego: on.",
      "The last light fell to you.",
      "They're still staring at the lights.",
      "Everyone else is in the dark. You made it so.",
      "A power move. A power outage, really.",
    ],
    draw: [
      "Nobody cleared it. The lights are still on. And so are the questions.",
      "Press cap reached. Dim result.",
      "The press limit hit. The lights won.",
      "Neither of you could kill the lights.",
      "The board stayed lit. The pride didn't.",
      "Too many presses, not enough solutions.",
      "You both ran out of presses and patience.",
      "The lights outlasted you both.",
      "A grid that refused to go dark.",
      "Lights: 1. Humans: 0.",
    ],
  },

  memory: {
    loss: [
      "Your memory is a sieve.",
      "You forgot where the pair was. They didn't.",
      "Goldfish: 1. You: 0.",
      "Somewhere, a card is still laughing at you.",
      "You remembered nothing. They remembered everything.",
      "They matched. You mismatched.",
      "Your brain is on a break.",
      "A fish just beat your memory.",
      "You forgot the one thing: where things are.",
      "The cards hide. They remember.",
      "Your hippocampus filed a complaint.",
      "You'll forget this defeat soon. Lucky.",
    ],
    win: [
      "Elephant memory, activated.",
      "You remember everything. Annoying.",
      "Every pair, no doubt. Brain: on.",
      "Photographic memory. Or luck. Say memory.",
      "You found every pair. Show-off.",
      "Your brain is a vault.",
      "You've got the memory of an elephant.",
      "They forgot. You remembered.",
      "A perfect recall performance.",
      "The cards didn't hide from you.",
      "Hippocampus: online.",
      "You remember where everything is. Even your keys?",
    ],
    draw: [
      "You tied. You both forgot who won.",
      "Equal pairs, equal forgetfulness.",
      "Nobody's memory won the day.",
      "A perfect tie: you each remembered half.",
      "A tie! Forgotten already?",
      "You both found the same amount. Impressive. Boring.",
      "Your brains are twins.",
      "You each forgot the same cards.",
      "A tie in the memory game. Ironic if you forget.",
      "Two goldfish, one result.",
      "You tied and you'll forget it.",
    ],
  },

  // game-over line by difficulty; nobody to taunt you, so keep them gentle
  2048: {
    "over-normal": [
      "Out of moves. Still, not bad.",
      "Tiles: everywhere. Moves: nowhere.",
      "One more merge from greatness.",
      "Normal mode: gentle. The grid: unforgiving.",
      "The grid is full. So is your potential.",
      "A fine run. The tiles had other ideas.",
      "Out of room. Not out of ideas.",
      "Just one more merge, you said.",
      "Somewhere, a 2048 tile is waiting for you.",
      "Don't worry, the next run will be perfect. (It won't.)",
      "You almost had it. Almost.",
      "Tile traffic jam: your move was blocked.",
    ],
    "over-hard": [
      "Hard mode doesn't do pity.",
      "The tiles were not on your side. They never are.",
      "Out of space, not out of dignity.",
      "Hard mode noticed you leaving.",
      "You can't merge your way out of every corner.",
      "Hard mode: where tiles hold grudges.",
      "The board remembers your mistakes.",
      "That didn't go as planned. Hard mode never does.",
      "You were swimming against the tide of 2s.",
      "You fought bravely. The grid fought dirty.",
      "A 4 appeared where you didn't want it.",
      "Space ran out faster than hope.",
      "The corner strategy had a flaw. Hard mode found it.",
    ],
    "over-brutal": [
      "Brutal. You knew what you signed up for.",
      "Brutal mode says: nice try.",
      "It doesn't care about you. It's a grid.",
      "Brutal is called brutal for a reason.",
      "That 4 landed exactly where it hurt. On purpose.",
      "It's not luck. It's malice.",
      "That wasn't random. That was personal.",
      "The grid placed that tile with love. Evil love.",
      "Brutal mode noticed your plan. And ruined it.",
      "The 2s were out to get you.",
      "That placement was surgical. Cruel, but surgical.",
      "Brutal mode was never fair. Never claimed to be.",
      "You lost to a machine with a grudge.",
    ],
  },
};
